version: '3'
services:
  express:
    build: ./backend
    ports:
      - "3000:8080"
    links:
      - mariadb
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - mariadb
  messenger:
    build: ./messenger
    ports:
      - "5000:3000"
    volumes:
      - ./messenger/.env:/app/.env:ro
    links:
      - express
  mariadb:
    image: mariadb
    volumes:
      - ${DB_MYSQL_HOME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
