version: '3'
services:
  express:
    build: .
    ports:
      - "3000:8080"
    links:
      - mariadb
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
      - ${DB_MYSQL_HOME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
