version: '3'
services:
  express:
    build: .
    ports:
      - "3000:8080"
    links:
      - mariadb
    volumes:
      - .:/app
    depends_on:
      - mariadb
    command: sh -c "yarn; yarn build; yarn watch"
  mariadb:
    image: mariadb
    volumes:
      - ${DB_MYSQL_HOME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
