service:
  name: citywatch-backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  main:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: /
